### ISSUE TITLE
Package TODO

### ISSUE THREAD

**Issue by lgatto** [lgatto/psm#1]
### Refactor

- [ ] Refer to parsers, rather then back-ends.

### Features

- [ ] Harmonize variable names for different parsers.
- [ ] Consider different back-ends: currently in memory, but on-disk would be useful for large data and direct compatibility with `Spectra` back-ends.
- [ ] Consider integration with `MSnID`; here a `data.table` back-end would be relevant.
- [ ] Infrastructure for identification data processing and analysis (peptide by protein contingency matrices, ... - see discussion with @Sjan1)
